<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude('var')
    ->exclude('vendor')
    ->exclude('tools')
    ->exclude('config/secrets')
    ->exclude('ai-agents')
    ->notPath('config/reference.php') // auto-generated (apps only); regenerated by the framework
;

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@PSR12' => true,
        'array_syntax' => ['syntax' => 'short'],
        'ordered_imports' => ['sort_algorithm' => 'alpha'],
        'no_unused_imports' => true,
        'single_quote' => true,
        'yoda_style' => true,
        // Greenfield project: fail-loud type contracts (no legacy coercion to break).
        // php-cs-fixer flags this "risky" only because it changes runtime behavior.
        'declare_strict_types' => true,
    ])
    ->setFinder($finder)
;
